# Generated by Django 5.2.8 on 2025-12-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('avatar_url', models.URLField(blank=True)),
                ('total_earning', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rank', models.PositiveIntegerField()),
                ('period', models.CharField(choices=[('today', 'Today'), ('week', 'This Week'), ('month', 'This Month'), ('all', 'All Time')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
