# Generated by Django 5.2.8 on 2025-12-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_paymentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='referral_code_used',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='sponsor_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
