# Generated by Django 5.2.8 on 2025-12-11 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_upgraderequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('tx_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
